# Generated by Django 5.2.4 on 2025-09-04 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('policy_number', models.CharField(max_length=255, unique=True)),
                ('car_model', models.CharField(blank=True, max_length=255, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('bank', 'bank')], max_length=100)),
                ('payment_status', models.CharField(choices=[('active', 'active'), ('complete', 'complete'), ('cancelled', 'cancelled')], max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reference_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.agentmodel')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.clientmodel')),
                ('insurance_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.insurancecompanymodel')),
            ],
        ),
        migrations.CreateModel(
            name='TranscationLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('cancelled', 'cancelled'), ('payment', 'payment'), ('credit_adjustment', 'credit_adjustment'), ('payback', 'payback')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.policymodel')),
            ],
        ),
    ]
