# Generated by Django 5.2.4 on 2025-09-16 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_vendormodel_policymodel_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policymodel',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy.agentmodel'),
        ),
        migrations.AlterField(
            model_name='policymodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy.clientmodel'),
        ),
        migrations.AlterField(
            model_name='policymodel',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy.insurancecompanymodel'),
        ),
        migrations.AlterField(
            model_name='policymodel',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy.vendormodel'),
        ),
    ]
